In [5]:
# load and summarize the housing dataset
import numpy as np
import pandas as pd
import warnings
import random
import seaborn as sns 

random.seed(7)


from matplotlib import pyplot as plt
from sklearn.linear_model import ElasticNet, LinearRegression
from sksurv.linear_model import CoxnetSurvivalAnalysis as CoxPH
from sksurv.metrics import concordance_index_censored
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.exceptions import FitFailedWarning
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from functools import reduce
from statsmodels.api import OLS, add_constant

In [11]:
coefs_it = pd.read_csv('coefs_frailty_cmb.csv')
scors_set2 = pd.read_csv('en_frailty_cmb_set2.csv')

In [12]:
combined_scores = np.load('combined_scores_frailty_cmb.npy')

In [20]:
metric_value = np.load('metric_frailty_cmb.npy')

In [29]:
metric_value

array([[0.24923281, 0.22509814],
       [0.2547288 , 0.22468149],
       [0.24929894, 0.22062259],
       [0.2580365 , 0.22557442],
       [0.26137268, 0.22700869],
       [0.25498851, 0.22268152],
       [0.25184223, 0.22648589],
       [0.23814239, 0.22290671],
       [0.25334294, 0.22364048],
       [0.24504581, 0.2261596 ],
       [0.24803376, 0.22288383],
       [0.26055618, 0.22505958],
       [0.25145583, 0.22373904],
       [0.24404295, 0.22616221],
       [0.25048374, 0.22252428],
       [0.2525659 , 0.22458343],
       [0.25065457, 0.229086  ],
       [0.25233265, 0.22621483],
       [0.25206764, 0.2290934 ],
       [0.24352164, 0.22589784],
       [0.23649935, 0.22573339],
       [0.25349165, 0.22650105],
       [0.25099149, 0.22539874],
       [0.25010318, 0.2255043 ],
       [0.24660947, 0.22271922],
       [0.24251063, 0.22487972],
       [0.25099753, 0.21910752],
       [0.24339362, 0.2223483 ],
       [0.25751128, 0.22122076],
       [0.25056722, 0.22668006],
       [0.

In [30]:
pcascore = np.load('../../rsquared/R2_cmb_met_pca.npy')
pcascore

array([0.15623804, 0.17245312])

In [32]:
samenscore = np.load('../../rsquared/R2_cmb_met.npy')
samenscore

array([0.25140018, 0.24186671])

In [33]:
mhscore = np.load('../../rsquared/R2_cmb_mh.npy')
mhscore

array([0.24467386, 0.23432267])